name: Deploy to BunnyCDN on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i && npm run build
      - uses: ayeressian/bunnycdn-storage-deploy@v2.2.3
        with:
            source: "dist"
            destination: "/"
            storageZoneName: "${{ secrets.STORAGE_NAME }}"
            storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
            accessKey: "${{ secrets.STORAGE_KEY }}"
            pullZoneId: "${{ secrets.ZONE_ID }}"
            upload: "true"
            remove: "true"
            purgePullZone: "true"